apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tyk-gateway
  namespace: tyk
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: tyk-gateway
    spec:
      containers:
      - image: tykio/tyk-gateway:latest
        imagePullPolicy: Always
        name: tyk-gateway
        env:
          - name: TYK_GW_STORAGE_HOST
            value: redis-1.default.svc.cluster.local
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: tyk-gateway-apps
            mountPath: /apps
          - name: tyk-gateway-conf
            mountPath: /etc/tyk-gateway
      volumes:
        - name: tyk-gateway-apps
          gcePersistentDisk:
            pdName: tyk-gateway
            fsType: ext4
        - name: tyk-gateway-conf
          configMap:
            name: tyk-gateway-conf
            items:
              - key: tyk.conf
                path: tyk.conf